version: "3.8"
services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: always
    working_dir: /app  # Match the Dockerfile's WORKDIR
    volumes:
      - .:/app  # Mount the project directory to /app
      - ./logs:/app/logs  # Ensure logs are written to the host
    env_file:
      - .env
