version: "3.8"
services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    volumes:
      - .:/app  # Mount the project directory to /app
      - ./logs:/app/logs  # Keep logs accessible on the host
    env_file:
      - .env
